spring:
  application:
    name: testcode
  datasource:
    url: jdbc:postgresql://localhost:5432/testcode?characterEncoding=UTF-8
    username: postgres
    password: postgres-first
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

logging:
  config: classpath:logback-local.xml